/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ohmin839.jybuben.api;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
